site_name: DXC-0
theme:
  name: material
  include_sidebar: false
  palette:
    scheme: slate
    primary: "black"
    accent: "green"
  favicon: 'assets/test.jpg'
  logo: 'assets/test.jpg'
  highlightjs: true
site_author: DXC-0
copyright: DXC-0
site_description: DXC-0 Linux Documentation
nav:
- 'About Me.md'
extra_css:
  - assets/custom.css
site_url: https://dxc-0.github.io/AboutMe/
use_directory_urls: false